# Generated by Django 4.2.10 on 2025-03-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
