# Generated by Django 5.1.4 on 2025-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'بررسی نشده'), ('accepted', 'موافقت شده'), ('rejected', 'رد شده')], default='waiting', max_length=20),
        ),
    ]
