# Generated by Django 5.1.4 on 2025-01-02 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_vacationrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreport',
            options={'verbose_name': 'ثبت خطا', 'verbose_name_plural': 'خطاهای ثبت شده'},
        ),
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'verbose_name': 'درخواست مرخصی', 'verbose_name_plural': 'درخواست های مرخصی'},
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='corrective_actions',
            field=models.TextField(blank=True, max_length=250, verbose_name='اقدامات اصلاحی'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='effective',
            field=models.BooleanField(default=True, verbose_name='مؤثر بوده/نبوده'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='prevention_actions',
            field=models.TextField(blank=True, max_length=250, verbose_name='اقدامات پیشگیری'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='type',
            field=models.CharField(max_length=50, verbose_name='نوع خطا'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_problem_reports', to=settings.AUTH_USER_MODEL, verbose_name='اعلام کننده'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='جایگزین'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='مدت'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='type',
            field=models.CharField(choices=[('hourly', 'ساعتی'), ('daily', 'روزانه')], max_length=20, verbose_name='نوع مرخصی'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vacation_req', to=settings.AUTH_USER_MODEL, verbose_name='نام متقاضی'),
        ),
    ]
