# Generated by Django 5.1.4 on 2025-01-02 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_problemreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('بررسی نشده', 'بررسی نشده'), ('موافقت شده', 'موافقت شده'), ('رد شده', 'رد شده')], default='بررسی نشده', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='type',
            field=models.CharField(choices=[('ساعتی', 'ساعتی'), ('روزانه', 'روزانه')], max_length=20, verbose_name='نوع مرخصی'),
        ),
    ]
