# Generated by Django 5.1.4 on 2025-01-03 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_vacationrequest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 10, 40, 24, 568082, tzinfo=datetime.timezone.utc)),
        ),
    ]
