# Generated by Django 5.1.4 on 2025-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_problemreport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
