# Generated by Django 5.1.4 on 2025-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_problemreport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('بررسی نشده', 'بررسی نشده'), ('موافقت شده', 'موافقت شده'), ('رد شده', 'رد شده')], default='بررسی نشده', max_length=20, verbose_name='وضعیت مرخصی'),
        ),
    ]
