# Generated by Django 4.2.10 on 2025-03-30 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0012_alter_vacationrequest_alternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='پیام')),
                ('type', models.CharField(choices=[('info', 'اطلاعیه'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('request', 'درخواست')], default='info', max_length=10, verbose_name='نوع اعلان')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک مرتبط')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
