# Generated by Django 4.2.10 on 2025-05-08 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('بررسی نشده', 'بررسی نشده'), ('بررسی بیشتر', 'بررسی بیشتر'), ('رد شده', 'رد شده'), ('تایید شده', 'تایید شده')], default='بررسی نشده', max_length=20, verbose_name='وضعیت تسک')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده؟')),
                ('remind_at', models.DateTimeField(verbose_name='یادآوری بعدی')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع تسک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('reminder', models.PositiveIntegerField(default=3, verbose_name='دوره یادآوری(روز)')),
                ('guide_file', models.FileField(blank=True, null=True, upload_to='task_guides/', verbose_name='فایل راهنما')),
                ('assigned_to', models.ManyToManyField(related_name='assigned_tasks', through='organization.TaskAssignment', to=settings.AUTH_USER_MODEL, verbose_name='انجام دهندگان')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'تسک',
                'verbose_name_plural': 'تسک ها',
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.todolist'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='انجام دهنده'),
        ),
    ]
