# Generated by Django 4.2.10 on 2025-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_taskassignment_todolist_delete_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='remind_at',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='reminder',
        ),
        migrations.AddField(
            model_name='todolist',
            name='remind_at',
            field=models.DateTimeField(default='2025-5-9 00:00:00', verbose_name='موعد'),
            preserve_default=False,
        ),
    ]
