# Generated by Django 4.2.10 on 2025-06-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
