# Generated by Django 4.2.10 on 2025-06-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
