# Generated by Django 4.2.10 on 2025-06-06 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0020_delete_messageread'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان خواندن')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_marks', to='organization.message', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت خوانده شدن پیام',
                'verbose_name_plural': 'وضعیت خوانده شدن پیام\u200cها',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
