# Generated by Django 4.2.10 on 2025-06-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_messageread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRead',
        ),
    ]
