# Generated by Django 4.2.10 on 2025-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_messageseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان صوت (ثانیه)'),
        ),
    ]
