# Generated by Django 4.2.10 on 2025-07-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_attachment_audio_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='audio_duration',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent',
        ),
    ]
