# Generated by Django 4.2.10 on 2025-07-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_remove_attachment_audio_duration_remove_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='وضعیت ارسال'),
        ),
    ]
