# Generated by Django 5.1.4 on 2025-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuyorder',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='productbuyorder',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='productbuyorder',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productbuyorder',
            name='name',
            field=models.CharField(error_messages={'required': 'این فیلد الزامی می باشد.'}, max_length=150, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='productbuyorder',
            name='order_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('immediate', 'فوری')], max_length=20, verbose_name='نوع سفارش'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='order_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('immediate', 'فوری')], max_length=20, verbose_name='نوع سفارش'),
        ),
    ]
