# Generated by Django 5.1.4 on 2025-01-02 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productbuyorder_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbuyorder',
            options={'verbose_name': 'درخواست خرید کالا', 'verbose_name_plural': 'درخواست های خرید کالا'},
        ),
        migrations.AlterModelOptions(
            name='productstockroomorder',
            options={'verbose_name': 'درخواست کالا از انبار', 'verbose_name_plural': 'درخواست های کالا از انبار'},
        ),
        migrations.AddField(
            model_name='productbuyorder',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='انجام شد'),
        ),
        migrations.AddField(
            model_name='productstockroomorder',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='انجام شد'),
        ),
        migrations.AlterField(
            model_name='productbuyorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buy_orders', to=settings.AUTH_USER_MODEL, verbose_name='نام متقاضی'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stock_orders', to=settings.AUTH_USER_MODEL, verbose_name='نام متقاضی'),
        ),
    ]
