# Generated by Django 5.1.4 on 2025-01-02 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productbuyorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuyorder',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productstockroomorder',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productbuyorder',
            name='order_type',
            field=models.CharField(choices=[('عادی', 'عادی'), ('فوری', 'فوری')], max_length=20, verbose_name='نوع سفارش'),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='order_type',
            field=models.CharField(choices=[('عادی', 'عادی'), ('فوری', 'فوری')], max_length=20, verbose_name='نوع سفارش'),
        ),
    ]
