# Generated by Django 5.1.4 on 2025-01-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productbuyorder_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbuyorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productstockroomorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
