# Generated by Django 5.1.4 on 2025-01-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, max_length=250, verbose_name='متن یادداشت'),
        ),
    ]
