# Generated by Django 5.1.4 on 2025-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuyorder',
            name='status',
            field=models.CharField(choices=[('بررسی نشده', 'بررسی نشده'), ('بررسی بیشتر', 'بررسی بیشتر'), ('موافقت شده', 'موافقت شده'), ('رد شده', 'رد شده')], default='بررسی نشده', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
