# Generated by Django 5.1.4 on 2025-03-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productbuyorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockroomorder',
            name='status',
            field=models.CharField(choices=[('بررسی نشده', 'بررسی نشده'), ('بررسی بیشتر', 'بررسی بیشتر'), ('موافقت شده', 'موافقت شده'), ('رد شده', 'رد شده')], default='بررسی نشده', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
